name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client rsync

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PYTHONANYWHERE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
          
          # Debug: verificar se a chave foi criada corretamente
          echo "SSH key file created:"
          ls -la ~/.ssh/id_rsa
          echo "First line of SSH key:"
          head -1 ~/.ssh/id_rsa
          
      - name: Testar conexão SSH
        run: |
          echo "Testing SSH connection to ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com"
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/id_rsa ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com "echo 'SSH connection successful'"

      - name: Copiar arquivos para PythonAnywhere via rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" \
            --exclude='.git' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.env' \
            --exclude='venv' \
            --exclude='.pytest_cache' \
            . ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com:/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api/

      - name: Rodar migrations no PythonAnywhere
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com \
          "cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api && source venv/bin/activate && python manage.py migrate"

      - name: Collect static files
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com \
          "cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api && source venv/bin/activate && python manage.py collectstatic --noinput"

      - name: Reload webapp via API
        run: |
          curl -X POST \
          -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
          https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_DOMAIN }}/reload/
