name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update && sudo apt-get install -y curl zip

      - name: Criar arquivo ZIP do projeto
        run: |
          zip -r bookstore-api.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.env*" "*venv*" "*.pytest_cache*"

      - name: Fazer upload via API do PythonAnywhere
        run: |
          curl -X POST \
            -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
            -F "file=@bookstore-api.zip" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/path/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api.zip

      - name: Extrair arquivos no PythonAnywhere
        run: |
          curl -X POST \
            -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
            -d "command=cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }} && unzip -o bookstore-api.zip -d bookstore-api && rm bookstore-api.zip" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/

      - name: Rodar migrations via API
        run: |
          curl -X POST \
            -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
            -d "command=cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api && source venv/bin/activate && python manage.py migrate" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/

      - name: Collect static files via API
        run: |
          curl -X POST \
            -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
            -d "command=cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bookstore-api && source venv/bin/activate && python manage.py collectstatic --noinput" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/

      - name: Reload webapp via API
        run: |
          curl -X POST \
          -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
          https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_DOMAIN }}/reload/
